#pragma once
#define MCST_MSG_Starting "< 최소경비확장트리 (MCST) 찾기 >"
#define MCST_MSG_Ending "< 프로그램을 마칩니다 >"
#define MCST_MSG_GetNumOfVertices "? 그래프의 vertex 수를 입력하시오 : "
#define MCST_MSG_GetNumOfEdges "? 그래프의 edge 수를 입력하시오 : "
#define MCST_MSG_StartingInputEdge1 "- 그래프의 edge를 반복하여"
#define MCST_MSG_StartingInputEdge2 "개 입력 받아야 합니다."
#define MCST_MSG_StartingInputEdge3 "하나의 edge는 (vertex1 vertext2 cost)의 순서로 표시됩니다."
#define MCST_MSG_InputEdge "? Edge를 입력하시오: "
#define MCST_MSG_Error_FirstVertex "[Error] 첫번째 vertex 번호가 범위를 벗어났습니다."
#define MCST_MSG_Error_SecondVertex "[Error] 두번째 vertex 번호가 범위를 벗어났습니다."
#define MCST_MSG_Error_Cost "[Error] 비용은 양수이어야 합니다."
#define MCST_MSG_Error_EdgeAlreadyExist "[Error] 이미 존재하는 edge 입니다."
#define MCST_MSG_ResultHead "! 최소비용확장트리의 edge들은 다음과 같습니다:"
#define MCST_MSG_EdgeDiscarded "Discard"
#define MCST_MSG_showHead "! 입력된 그래프는 다음과 같습니다:"
#define MCST_MSG_EdgeAdded " Add to MCST"
#define MAIN_MSG_END " <프로그램을 마칩니다.>"
#define MCST_MSG_StartSearch "! 최소비용확장트리를 찾기 시작합니다:"
#define MCST_MSG_Notice "- 그래프의 vertex 수와 edge 수를 입력 받아야 합니다."